### ISSUE TITLE
hds link detector no longer works with Asia Insight 

### ISSUE THREAD

**Issue by jimdays2788** [8HoLoN/Extension-HDS-Link-Detector#2]
http://www3.nhk.or.jp/nhkworld/en/tv/asiainsight/
Firefox HDS link detector used to work with above videos, but no more (using Windows 7 computer).
Chrome HDS link addon also doesn't work. I have almost zero computer ability, so forgive me if I haven't put this complaint in the correct place.

**Comment by 8HoLoN** [comment]
Hello,

After deep analysis, it appears that this web site rely on HLS technologies (video/mp2t => multiple .ts file chunks) and not on the HDS technologie.
Multiple .ts file chunks.
Specific development is necessary to adapt this extension if you want to be able to recover the videos coming from this site. Or it might also be preferable to make a custom solution if you can not find one.

Regards,

**Comment by 8HoLoN** [comment]
Hello,

After deep analysis, it appears that this web site rely on HLS technologies (video/mp2t => multiple .ts file chunks) and not on the HDS technology.
Specific development is necessary to adapt this extension if you want to be able to recover the videos coming from this site. Or it might also be preferable to make a custom solution if you can not find one.

Regards,

**Comment by jimdays2788** [comment]
Thank you for the fast reply. I can use youtube-dl to get these videos. If you look at the following link, at my post near the bottom of the thread, I show how to do it.
IQ required is 99.3.  Verified by IQmaster.com
http://forum.videohelp.com/threads/381179-Need-help-with-Adobe-HDS-Link-Detector-to-get-join-this-video

**Comment by 8HoLoN** [comment]
OK, thank you for the link. However, I don't get the part "IQ required is 99.3. Verified by IQmaster.com" of your message, any hint ?
